### ISSUE TITLE
backward compatibility of calling interfaces

### ISSUE THREAD

**Issue by KaymeKaydex** [KaymeKaydex/go-vshard-router#10]
Now when a procedure is called, a map, a getTyped function, and an error are returned. It is necessary to make it possible to use compatible interfaces, or to refactor the response from the library

**Comment by hackallcode** [comment]
I have a same code:

```go
res := crud.MakeResult(reflect.TypeOf(User{}))
myTtRequest := tarantool.NewCallRequest("get").Args([]any{"test"})
ftr := connPool.Do(myTtRequest, pool.ANY)
err := ftr.GetTyped(&res)
```

So, I want to use something as this:

```go
res := crud.MakeResult(reflect.TypeOf(User{}))
myVshardRequest := vshard.NewCallRequest("get").Args([]any{"test"}).BucketId(1000)
ftr := vshardRouter.Do(myVshardRequest, pool.ANY)
err := ftr.GetTyped(&res)
```

You can notice that the fundamental difference is only in the second line.

So, to get raw result, I want to use Get() function, as in original go-connector:

```go
myVshardRequest := vshard.NewCallRequest("get").Args([]any{"test"}).BucketId(1000)
ftr := vshardRouter.Do(myVshardRequest, pool.ANY)
res, err := ftr.Get()
```

**Comment by KaymeKaydex** [comment]
we need to make a sugar router, we will not be able to support the same signatures as in go-tarantool because for the go-tarantool ecosystem “Request” and other are closed faces
