### ISSUE TITLE
Write a single error/response type with states and do decoding once

### ISSUE THREAD

**Issue by KaymeKaydex** [KaymeKaydex/go-vshard-router#100]
tmp description
```

BenchmarkTestMsgpackDecodeErrors-8        3118     348698 ns/op
BenchmarkTestMsgpackDecodeErrors-8        2929     352175 ns/op
BenchmarkTestMsgpackDecodeErrors-8        3298     351561 ns/op

```

```
BenchmarkTestMsgpackDecodeErrors-8        2941     345167 ns/op
BenchmarkTestMsgpackDecodeErrors-8        3339     344878 ns/op
```

разница в декодинге

Вообще надо превратить декодинг в единый блок и в один тип ошибки

И эта ошибка может декодиться либо в vshard error, либо в assert error в зависимости от ситуации входящего сообщения и не вызывать несколько раз get Typed и Get()

Короче можно прямо хороший boost up выжать если сделать в 1ин тип ошибки возвращаемые

Ну то есть процентов на 10 ускорить общую обработку ответов за счет того что мы не несколько раз в интерфейсы и еще куда-то гоняем, а сразу правильно обрабатываем этот специфичный ответ

Ну то есть ответ должен содержать rawResp в виде слайса пустых интерфейсов, и 2 ошибки которые могут быть Нил это асерт и вшард ошибки, а так же «стейт» ответа
И сразу считывать туда 1им присестом, и там же обрабатывать мисматчи если формат ответа неправильный

А в функции getTyped принимать новый тип который мы определим как дженерик, а в метод ему напишем декод мсгпака где первое поле скипаем потому что там бул который юзеру не интересен

Или если можно сохранять на стейте декодинга отдельно выделенные поля на которые натравлен декодер то делать так

**Comment by KaymeKaydex** [comment]
#99

**Comment by nurzhan-saktaganov** [comment]
Custom decoder for 'vshard.storage.call' in #99 (partially resolves this issue)
