### ISSUE TITLE
Impossible to call function with several results

### ISSUE THREAD

**Issue by hackallcode** [KaymeKaydex/go-vshard-router#11]
I have a function that does one action: `return 1, 2`. So I call it by `RouterCallImpl` and it returns the error `cant get call cause call impl timeout`.

**Comment by hackallcode** [comment]
The same error occurs if the function does `return nil, 2`

**Comment by hackallcode** [comment]
The problem is that the `RouterCallImpl` expects there to be 2 values in the result, but `vshard.storage.call` returns true/false + all parameters from the function (zero parameters also is correct). The example above returns `true, 1, 2, 3`. If you create a function with `return`, the result will only be `true`.

**Comment by KaymeKaydex** [comment]
#13 it seems this pr should solve the problem
